<a href="https://colab.research.google.com/github/jaimeisaac2020/Python-analsisis-basicos/blob/mi-github/3_2penamultivariante.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

# Datos
X1 = np.array([2, 1, 2, 2])
X2 = np.array([3, 5, 2, 3])
X3 = np.array([-1, -2, 1, 1])
datos = np.vstack((X1, X2, X3)).T

# Vector de medias
medias = np.mean(datos, axis=0)
print("Vector de medias:")
print(medias)

# Matriz de varianzas y covarianzas
S = np.cov(datos, rowvar=False)
print("Matriz de varianzas y covarianzas:")
print(S)

# Varianza generalizada (determinante de S)
var_generalizada = np.linalg.det(S)
print("Varianza generalizada:")
print(var_generalizada)

# Matriz de correlación
R = np.corrcoef(datos, rowvar=False)
print("Matriz de correlación:")
print(R)

# Raíz y vector característico mayor
valores_propios, vectores_propios = np.linalg.eig(S)
valor_propio_mayor = np.max(valores_propios)
vector_propio_mayor = vectores_propios[:, np.argmax(valores_propios)]
print("Valor propio mayor:")
print(valor_propio_mayor)
print("Vector propio asociado:")
print(vector_propio_mayor)

Vector de medias:
[ 1.75  3.25 -0.25]
Matriz de varianzas y covarianzas:
[[ 0.25       -0.58333333  0.58333333]
 [-0.58333333  1.58333333 -1.58333333]
 [ 0.58333333 -1.58333333  2.25      ]]
Varianza generalizada:
0.037037037037037084
Matriz de correlación:
[[ 1.         -0.92717265  0.77777778]
 [-0.92717265  1.         -0.83887049]
 [ 0.77777778 -0.83887049  1.        ]]
Valor propio mayor:
3.7283804118858836
Vector propio asociado:
[ 0.22972006 -0.61765788  0.75214855]
