<a href="https://colab.research.google.com/github/jaimeisaac2020/Python-analsisis-basicos/blob/mi-github/newtonsabados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ejemplo 1 de la clase de hoy Sabado 12 de Marzo de 2022
## Resolver $f(x)=4cos(x)-e^{x}$

In [ ]:
# Método de Newton-Raphson
# Ejemplo 1 

import numpy as np

# INGRESO
fx  = lambda x: 4*np.cos(x)-np.exp(x)
dfx = lambda x: -4*np.sin(x)-np.exp(x)

x0 = 2
tolera = 0.0000001

# PROCEDIMIENTO
tabla = []
tramo = abs(2*tolera)
xi = x0
while (tramo>=tolera):
    xnuevo = xi - fx(xi)/dfx(xi)
    tramo  = abs(xnuevo-xi)
    tabla.append([xi,xnuevo,tramo])
    xi = xnuevo

# convierte la lista a un arreglo.
tabla = np.array(tabla)
n = len(tabla)

# SALIDA
print(['xi', 'xnuevo', 'tramo'])
np.set_printoptions(precision = 4)
print(tabla)
print('raiz en: ', xi)
print('con error de: ',tramo)


['xi', 'xnuevo', 'tramo']
[[2.0000e+00 1.1789e+00 8.2110e-01]
 [1.1789e+00 9.3089e-01 2.4801e-01]
 [9.3089e-01 9.0508e-01 2.5814e-02]
 [9.0508e-01 9.0479e-01 2.9243e-04]
 [9.0479e-01 9.0479e-01 3.7628e-08]]
raiz en:  0.9047882178730194
con error de:  3.762819067443246e-08


# Ejemplo 2 de la clase de hoy

## Resolver $f(x)=3x+sen(x)-e^{x}$ en $[0,1]$

In [ ]:
# Método de Newton-Raphson
# Ejemplo 1 

import numpy as np

# INGRESO
fx  = lambda x: 3*x+np.sin(x)-np.exp(x)
dfx = lambda x: 3+np.cos(x)-np.exp(x)

x0 = 0.5
tolera = 0.0000001

# PROCEDIMIENTO
tabla = []
tramo = abs(2*tolera)
xi = x0
while (tramo>=tolera):
    xnuevo = xi - fx(xi)/dfx(xi)
    tramo  = abs(xnuevo-xi)
    tabla.append([xi,xnuevo,tramo])
    xi = xnuevo

# convierte la lista a un arreglo.
tabla = np.array(tabla)
n = len(tabla)

# SALIDA
print(['xi', 'xnuevo', 'tramo'])
np.set_printoptions(precision = 4)
print(tabla)
print('raiz en: ', xi)
print('con error de: ',tramo)


['xi', 'xnuevo', 'tramo']
[[5.0000e-01 3.5163e-01 1.4837e-01]
 [3.5163e-01 3.6039e-01 8.7681e-03]
 [3.6039e-01 3.6042e-01 2.7237e-05]
 [3.6042e-01 3.6042e-01 2.6488e-10]]
raiz en:  0.3604217029603244
con error de:  2.6487645410355753e-10


# Otros Ejemplos

## Resolver $f(x)=x^3+4x^2-10$

In [ ]:
# Método de Newton-Raphson
# 

import numpy as np

# INGRESO
fx  = lambda x: x**3 + 4*(x**2) - 10
dfx = lambda x: 3*(x**2) + 8*x

x0 = 2
tolera = 0.0000001

# PROCEDIMIENTO
tabla = []
tramo = abs(2*tolera)
xi = x0
while (tramo>=tolera):
    xnuevo = xi - fx(xi)/dfx(xi)
    tramo  = abs(xnuevo-xi)
    tabla.append([xi,xnuevo,tramo])
    xi = xnuevo

# convierte la lista a un arreglo.
tabla = np.array(tabla)
n = len(tabla)

# SALIDA
print(['xi', 'xnuevo', 'tramo'])
np.set_printoptions(precision = 4)
print(tabla)
print('raiz en: ', xi)
print('con error de: ',tramo)


In [ ]:
# Método de Newton-Raphson


import numpy as np

# INGRESO
fx  = lambda x: np.exp(x)+2**(-x)+2*np.cos(x)-6
dfx = lambda x: np.exp(x)-2**(-x)*np.log(2)-2*np.sin(x)

x0 = 1/3
tolera = 0.0000001

# PROCEDIMIENTO
tabla = []
tramo = abs(2*tolera)
xi = x0
while (tramo>=tolera):
    xnuevo = xi - fx(xi)/dfx(xi)
    tramo  = abs(xnuevo-xi)
    tabla.append([xi,xnuevo,tramo])
    xi = xnuevo

# convierte la lista a un arreglo.
tabla = np.array(tabla)
n = len(tabla)

# SALIDA
print(['xi', 'xnuevo', 'tramo'])
np.set_printoptions(precision = 4)
print(tabla)
print('raiz en: ', xi)
print('con error de: ',tramo)


['xi', 'xnuevo', 'tramo']
[[3.3333e-01 1.0386e+01 1.0053e+01]
 [1.0386e+01 9.3862e+00 9.9973e-01]
 [9.3862e+00 8.3869e+00 9.9934e-01]
 [8.3869e+00 7.3881e+00 9.9879e-01]
 [7.3881e+00 6.3901e+00 9.9795e-01]
 [6.3901e+00 5.3965e+00 9.9366e-01]
 [5.3965e+00 4.4246e+00 9.7189e-01]
 [4.4246e+00 3.5231e+00 9.0152e-01]
 [3.5231e+00 2.7676e+00 7.5549e-01]
 [2.7676e+00 2.2238e+00 5.4384e-01]
 [2.2238e+00 1.9252e+00 2.9860e-01]
 [1.9252e+00 1.8365e+00 8.8694e-02]
 [1.8365e+00 1.8294e+00 7.0368e-03]
 [1.8294e+00 1.8294e+00 4.1739e-05]
 [1.8294e+00 1.8294e+00 1.4605e-09]]
raiz en:  1.8293836019338487
con error de:  1.460484844173493e-09


In [ ]:
import scipy.optimize as opt
opt.newton(fx,x0, fprime=dfx, tol = tolera)

0.9047882178730194

## Resolver $f(x)=-x^3-cos(x)$

In [ ]:
# Método de Newton-Raphson
# 

import numpy as np

# INGRESO
fx  = lambda x: -x**3-np.cos(x)
dfx = lambda x: -3*(x**2)+np.sin(x)

x0 = -1
tolera = 0.0000001

# PROCEDIMIENTO
tabla = []
tramo = abs(2*tolera)
xi = x0
while (tramo>=tolera):
    xnuevo = xi - fx(xi)/dfx(xi)
    tramo  = abs(xnuevo-xi)
    tabla.append([xi,xnuevo,tramo])
    xi = xnuevo

# convierte la lista a un arreglo.
tabla = np.array(tabla)
n = len(tabla)

# SALIDA
print(['xi', 'xnuevo', 'tramo'])
np.set_printoptions(precision = 4)
print(tabla)
print('raiz en: ', xi)
print('con error de: ',tramo)

['xi', 'xnuevo', 'tramo']
[[-1.0000e+00 -8.8033e-01  1.1967e-01]
 [-8.8033e-01 -8.6568e-01  1.4649e-02]
 [-8.6568e-01 -8.6547e-01  2.1009e-04]
 [-8.6547e-01 -8.6547e-01  4.2851e-08]]
raiz en:  -0.8654740331016162
con error de:  4.28513607930725e-08


In [ ]:
import numpy as np

# INGRESO
fx  = lambda x: -x**3-np.cos(x)
dfx = lambda x: -3*(x**2)+np.sin(x)

In [ ]:
import scipy.optimize as opt
opt.newton(fx,x0, fprime=dfx, tol = tolera)

-0.8654740331016162

## Resolver $F(x)=e^x-2^x+cos(x)-2$

In [ ]:
# Método de Newton-Raphson
# 

import numpy as np

# INGRESO
fx  = lambda x: np.exp(x)+2**(-x)+2*np.cos(x)-2
dfx = lambda x: np.exp(x)+(2**(-x))*(np.log(2))*(-1)-2*np.sin(x)

x0 = 1.5
tolera = 0.00001

# PROCEDIMIENTO
tabla = []
tramo = abs(2*tolera)
xi = x0
while (tramo>=tolera):
    xnuevo = xi - fx(xi)/dfx(xi)
    tramo  = abs(xnuevo-xi)
    tabla.append([xi,xnuevo,tramo])
    xi = xnuevo

# convierte la lista a un arreglo.
tabla = np.array(tabla)
n = len(tabla)

# SALIDA
print(['xi', 'xnuevo', 'tramo'])
np.set_printoptions(precision = 4)
print(tabla)
print('raiz en: ', xi)
print('con error de: ',tramo)


['xi', 'xnuevo', 'tramo']
[[ 1.5000e+00  1.7208e-01  1.3279e+00]
 [ 1.7208e-01 -8.7189e+00  8.8910e+00]
 [-8.7189e+00 -7.2819e+00  1.4370e+00]
 ...
 [-2.4736e+00 -1.6550e+00  8.1858e-01]
 [-1.6550e+00 -1.1157e+03  1.1140e+03]
 [-1.1157e+03         nan         nan]]
raiz en:  nan
con error de:  nan


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: RuntimeWarning: overflow encountered in double_scalars
  import sys
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:8: RuntimeWarning: overflow encountered in double_scalars
  
/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:18: RuntimeWarning: invalid value encountered in double_scalars


In [ ]:
# Método de Newton-Raphson
# 

import numpy as np

# INGRESO
fx  = lambda x:np.log(x-1)+np.cos(x-1)
dfx = lambda x: (1/(x-1))-np.sin(x-1)

x0 = 1.4
tolera = 0.00001

# PROCEDIMIENTO
tabla = []
tramo = abs(2*tolera)
xi = x0
while (tramo>=tolera):
    xnuevo = xi - fx(xi)/dfx(xi)
    tramo  = abs(xnuevo-xi)
    tabla.append([xi,xnuevo,tramo])
    xi = xnuevo

# convierte la lista a un arreglo.
tabla = np.array(tabla)
n = len(tabla)

# SALIDA
print(['xi', 'xnuevo', 'tramo'])
np.set_printoptions(precision = 4)
print(tabla)
print('raiz en: ', xi)
print('con error de: ',tramo)


['xi', 'xnuevo', 'tramo']
[[1.4000e+00 1.3977e+00 2.2602e-03]
 [1.3977e+00 1.3977e+00 8.6405e-06]]
raiz en:  1.397748475831618
con error de:  8.640517190183772e-06


In [ ]:
# Método de Newton-Raphson
# 

import numpy as np

# INGRESO
#fx  = lambda x:2*x*(np.cos(2*x))-(x-2)**2
#dfx = lambda x: 

x0 = 1.4
tolera = 0.00001

# PROCEDIMIENTO
tabla = []
tramo = abs(2*tolera)
xi = x0
while (tramo>=tolera):
    xnuevo = xi - fx(xi)/dfx(xi)
    tramo  = abs(xnuevo-xi)
    tabla.append([xi,xnuevo,tramo])
    xi = xnuevo

# convierte la lista a un arreglo.
tabla = np.array(tabla)
n = len(tabla)

# SALIDA
print(['xi', 'xnuevo', 'tramo'])
np.set_printoptions(precision = 4)
print(tabla)
print('raiz en: ', xi)
print('con error de: ',tramo)

['xi', 'xnuevo', 'tramo']
[[1.4000e+00 1.3977e+00 2.2602e-03]
 [1.3977e+00 1.3977e+00 8.6405e-06]]
raiz en:  1.397748475831618
con error de:  8.640517190183772e-06


# Ejercicios para hacer en clase
## Resolver usando el metodo de Newton Raphson realizando 5 iteraciones.
+ $f(x)=x^3-3x+4$
+ $g(x)=x+cos(x)$

In [ ]:
# Método de Newton-Raphson
# 

import numpy as np

# INGRESO
#fx  = lambda x:2*x*(np.cos(2*x))-(x-2)**2
#dfx = lambda x: 

x0 = 1.4
tolera = 0.0001

# PROCEDIMIENTO
tabla = []
tramo = abs(2*tolera)
xi = x0
while (tramo>=tolera):
    xnuevo = xi - fx(xi)/dfx(xi)
    tramo  = abs(xnuevo-xi)
    tabla.append([xi,xnuevo,tramo])
    xi = xnuevo

# convierte la lista a un arreglo.
tabla = np.array(tabla)
n = len(tabla)

# SALIDA
print(['xi', 'xnuevo', 'tramo'])
np.set_printoptions(precision = 4)
print(tabla)
print('raiz en: ', xi)
print('con error de: ',tramo)

In [ ]:
# Método de Newton-Raphson
# 

import numpy as np

# INGRESO
fx  = lambda x: 20*x**3+24*x**2-12*x-5
dfx = lambda x: 60*x**2+48*x-12*x

x0 = -2
tolera = 0.0000001

# PROCEDIMIENTO
tabla = []
tramo = abs(2*tolera)
xi = x0
while (tramo>=tolera):
    xnuevo = xi - fx(xi)/dfx(xi)
    tramo  = abs(xnuevo-xi)
    tabla.append([xi,xnuevo,tramo])
    xi = xnuevo

# convierte la lista a un arreglo.
tabla = np.array(tabla)
n = len(tabla)

# SALIDA
print(['xi', 'xnuevo', 'tramo'])
np.set_printoptions(precision = 4)
print(tabla)
print('raiz en: ', xi)
print('con error de: ',tramo)

['xi', 'xnuevo', 'tramo']
[[-2.0000e+00 -1.7321e+00  2.6786e-01]
 [-1.7321e+00 -1.5949e+00  1.3723e-01]
 [-1.5949e+00 -1.5324e+00  6.2520e-02]
 [-1.5324e+00 -1.5065e+00  2.5921e-02]
 [-1.5065e+00 -1.4963e+00  1.0167e-02]
 [-1.4963e+00 -1.4924e+00  3.8852e-03]
 [-1.4924e+00 -1.4910e+00  1.4688e-03]
 [-1.4910e+00 -1.4904e+00  5.5295e-04]
 [-1.4904e+00 -1.4902e+00  2.0783e-04]
 [-1.4902e+00 -1.4901e+00  7.8071e-05]
 [-1.4901e+00 -1.4901e+00  2.9320e-05]
 [-1.4901e+00 -1.4901e+00  1.1010e-05]
 [-1.4901e+00 -1.4901e+00  4.1344e-06]
 [-1.4901e+00 -1.4901e+00  1.5525e-06]
 [-1.4901e+00 -1.4901e+00  5.8296e-07]
 [-1.4901e+00 -1.4901e+00  2.1890e-07]
 [-1.4901e+00 -1.4901e+00  8.2198e-08]]
raiz en:  -1.4900688754558749
con error de:  8.219829417122071e-08
